name: Playground

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'

jobs:
  play_around:
    runs-on: ubuntu-latest
    steps:
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Print the version
        run: |
          echo ${{ steps.get_version.outputs.VERSION }}
          echo "${{ github.event.inputs.version }}"
