name: Playground

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'

jobs:
  play_around:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Version
        run: |
          git config user.email ${{ secrets.AUTHOR_EMAIL }}
          git config user.name ${{ secrets.AUTHOR_NAME }}
          yarn version --new-version ${{ github.event.inputs.version }}
          git push origin main
