name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://npm.pkg.github.com/
      - name: Build
        run: |
          yarn
          yarn build
      - name: Version
        run: |
          yarn version --new-version ${{ github.event.inputs.version }}
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
